/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRegistrationContract__factory } from "./IRegistrationContract__factory";
export { VoterRegistrationContract__factory } from "./VoterRegistrationContract__factory";
