/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRegistrationContract__factory } from "./IRegistrationContract__factory";
export { IVoterRegistrationContract__factory } from "./IVoterRegistrationContract__factory";
export { IVotingAndTallyingContract__factory } from "./IVotingAndTallyingContract__factory";
export { LSAGVotingSystemTest__factory } from "./LSAGVotingSystemTest__factory";
