/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVoterRegistrationContract,
  IVoterRegistrationContractInterface,
} from "../../LSAGVotingSystemTest.sol/IVoterRegistrationContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "voterIndex",
        type: "uint256",
      },
    ],
    name: "isRegistered",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "lsagSignature",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "votingPublicKey",
        type: "bytes",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVoterRegistrationContract__factory {
  static readonly abi = _abi;
  static createInterface(): IVoterRegistrationContractInterface {
    return new Interface(_abi) as IVoterRegistrationContractInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVoterRegistrationContract {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IVoterRegistrationContract;
  }
}
