/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRegistrationContract__factory } from "./IRegistrationContract__factory";
export { IVoterRegistrationContract__factory } from "./IVoterRegistrationContract__factory";
export { VotingAndTallyingContract__factory } from "./VotingAndTallyingContract__factory";
