/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRegistrationContract } from "./IRegistrationContract";
export type { VoterRegistrationContract } from "./VoterRegistrationContract";
