/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IRegistrationContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "electionAuthority"
      | "electionId"
      | "electionSetup"
      | "getCandidates"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "electionAuthority",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "electionId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "electionSetup",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCandidates",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "electionAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "electionId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "electionSetup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCandidates",
    data: BytesLike
  ): Result;
}

export interface IRegistrationContract extends BaseContract {
  connect(runner?: ContractRunner | null): IRegistrationContract;
  waitForDeployment(): Promise<this>;

  interface: IRegistrationContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  electionAuthority: TypedContractMethod<[], [string], "view">;

  electionId: TypedContractMethod<[], [string], "view">;

  electionSetup: TypedContractMethod<[], [boolean], "view">;

  getCandidates: TypedContractMethod<[], [string[]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "electionAuthority"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "electionId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "electionSetup"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getCandidates"
  ): TypedContractMethod<[], [string[]], "view">;

  filters: {};
}
