/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRegistrationContract } from "./IRegistrationContract";
export type { IVoterRegistrationContract } from "./IVoterRegistrationContract";
export type { IVotingAndTallyingContract } from "./IVotingAndTallyingContract";
export type { LSAGVotingSystemTest } from "./LSAGVotingSystemTest";
