/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "RegistrationContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RegistrationContract__factory>;
    getContractFactory(
      name: "IRegistrationContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRegistrationContract__factory>;
    getContractFactory(
      name: "VoterRegistrationContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VoterRegistrationContract__factory>;
    getContractFactory(
      name: "IRegistrationContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRegistrationContract__factory>;
    getContractFactory(
      name: "IVoterRegistrationContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVoterRegistrationContract__factory>;
    getContractFactory(
      name: "VotingAndTallyingContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VotingAndTallyingContract__factory>;

    getContractAt(
      name: "RegistrationContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RegistrationContract>;
    getContractAt(
      name: "IRegistrationContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRegistrationContract>;
    getContractAt(
      name: "VoterRegistrationContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VoterRegistrationContract>;
    getContractAt(
      name: "IRegistrationContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRegistrationContract>;
    getContractAt(
      name: "IVoterRegistrationContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVoterRegistrationContract>;
    getContractAt(
      name: "VotingAndTallyingContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VotingAndTallyingContract>;

    deployContract(
      name: "RegistrationContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RegistrationContract>;
    deployContract(
      name: "IRegistrationContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRegistrationContract>;
    deployContract(
      name: "VoterRegistrationContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VoterRegistrationContract>;
    deployContract(
      name: "IRegistrationContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRegistrationContract>;
    deployContract(
      name: "IVoterRegistrationContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVoterRegistrationContract>;
    deployContract(
      name: "VotingAndTallyingContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VotingAndTallyingContract>;

    deployContract(
      name: "RegistrationContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RegistrationContract>;
    deployContract(
      name: "IRegistrationContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRegistrationContract>;
    deployContract(
      name: "VoterRegistrationContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VoterRegistrationContract>;
    deployContract(
      name: "IRegistrationContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRegistrationContract>;
    deployContract(
      name: "IVoterRegistrationContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVoterRegistrationContract>;
    deployContract(
      name: "VotingAndTallyingContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VotingAndTallyingContract>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
