/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lsagVotingSystemTestSol from "./LSAGVotingSystemTest.sol";
export type { lsagVotingSystemTestSol };
import type * as voterRegistrationContractSol from "./VoterRegistrationContract.sol";
export type { voterRegistrationContractSol };
import type * as votingAndTallyingContractSol from "./VotingAndTallyingContract.sol";
export type { votingAndTallyingContractSol };
export type { Lock } from "./Lock";
export type { RegistrationContract } from "./RegistrationContract";
export * as factories from "./factories";
export { Lock__factory } from "./factories/Lock__factory";
export type { IRegistrationContract } from "./LSAGVotingSystemTest.sol/IRegistrationContract";
export { IRegistrationContract__factory } from "./factories/LSAGVotingSystemTest.sol/IRegistrationContract__factory";
export type { IVoterRegistrationContract } from "./LSAGVotingSystemTest.sol/IVoterRegistrationContract";
export { IVoterRegistrationContract__factory } from "./factories/LSAGVotingSystemTest.sol/IVoterRegistrationContract__factory";
export type { IVotingAndTallyingContract } from "./LSAGVotingSystemTest.sol/IVotingAndTallyingContract";
export { IVotingAndTallyingContract__factory } from "./factories/LSAGVotingSystemTest.sol/IVotingAndTallyingContract__factory";
export type { LSAGVotingSystemTest } from "./LSAGVotingSystemTest.sol/LSAGVotingSystemTest";
export { LSAGVotingSystemTest__factory } from "./factories/LSAGVotingSystemTest.sol/LSAGVotingSystemTest__factory";
export { RegistrationContract__factory } from "./factories/RegistrationContract__factory";
export type { VoterRegistrationContract } from "./VoterRegistrationContract.sol/VoterRegistrationContract";
export { VoterRegistrationContract__factory } from "./factories/VoterRegistrationContract.sol/VoterRegistrationContract__factory";
export type { VotingAndTallyingContract } from "./VotingAndTallyingContract.sol/VotingAndTallyingContract";
export { VotingAndTallyingContract__factory } from "./factories/VotingAndTallyingContract.sol/VotingAndTallyingContract__factory";
