/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as voterRegistrationContractSol from "./VoterRegistrationContract.sol";
export type { voterRegistrationContractSol };
import type * as votingAndTallyingContractSol from "./VotingAndTallyingContract.sol";
export type { votingAndTallyingContractSol };
export type { RegistrationContract } from "./RegistrationContract";
export * as factories from "./factories";
export { RegistrationContract__factory } from "./factories/RegistrationContract__factory";
export type { IRegistrationContract } from "./VoterRegistrationContract.sol/IRegistrationContract";
export { IRegistrationContract__factory } from "./factories/VoterRegistrationContract.sol/IRegistrationContract__factory";
export type { VoterRegistrationContract } from "./VoterRegistrationContract.sol/VoterRegistrationContract";
export { VoterRegistrationContract__factory } from "./factories/VoterRegistrationContract.sol/VoterRegistrationContract__factory";
export type { IVoterRegistrationContract } from "./VotingAndTallyingContract.sol/IVoterRegistrationContract";
export { IVoterRegistrationContract__factory } from "./factories/VotingAndTallyingContract.sol/IVoterRegistrationContract__factory";
export type { VotingAndTallyingContract } from "./VotingAndTallyingContract.sol/VotingAndTallyingContract";
export { VotingAndTallyingContract__factory } from "./factories/VotingAndTallyingContract.sol/VotingAndTallyingContract__factory";
