/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { ECDSA } from "./@openzeppelin/contracts/utils/cryptography/ECDSA";
export { ECDSA__factory } from "./factories/@openzeppelin/contracts/utils/cryptography/ECDSA__factory";
export type { EVoting } from "./contracts/Evoting.sol/EVoting";
export { EVoting__factory } from "./factories/contracts/Evoting.sol/EVoting__factory";
export type { RegistrationContract } from "./contracts/RegistrationContract";
export { RegistrationContract__factory } from "./factories/contracts/RegistrationContract__factory";
export type { IRegistrationContract } from "./contracts/VoterRegistrationContract.sol/IRegistrationContract";
export { IRegistrationContract__factory } from "./factories/contracts/VoterRegistrationContract.sol/IRegistrationContract__factory";
export type { VoterRegistrationContract } from "./contracts/VoterRegistrationContract.sol/VoterRegistrationContract";
export { VoterRegistrationContract__factory } from "./factories/contracts/VoterRegistrationContract.sol/VoterRegistrationContract__factory";
export type { IVoterRegistrationContract } from "./contracts/VotingAndTallyingContract.sol/IVoterRegistrationContract";
export { IVoterRegistrationContract__factory } from "./factories/contracts/VotingAndTallyingContract.sol/IVoterRegistrationContract__factory";
export type { VotingAndTallyingContract } from "./contracts/VotingAndTallyingContract.sol/VotingAndTallyingContract";
export { VotingAndTallyingContract__factory } from "./factories/contracts/VotingAndTallyingContract.sol/VotingAndTallyingContract__factory";
